### ISSUE TITLE
Move to styled-components

### ISSUE THREAD

**Issue by mpacer** [Netflix-Skunkworks/commuter#4]
Move away from styled-jsx  to styled components

- [x] view(M )
- [x] header (M )
- [x] text (M )
- [x] directory-listing (M )
- [x] browse-header (M )
- [x] zeppelin (Shelby )
- [x] clone (Shelby )
- [x] ~discover (Shelby )~ *discover was removed*

**Comment by mpacer** [comment]
@stormpython @rgbkrk

**Comment by stormpython** [comment]
@mpacer ok, I will checkout your branch, add the last 3 files today.

**Comment by rgbkrk** [comment]
Ok, with our current PRs in flight we're all set internally once those are merged. We still need to upgrade the components we're using so that we are using the newer `@nteract/*` components all use `styled-components` rather than the older versions that relied on `styled-jsx`. Progress for that is in #5.

**Comment by stormpython** [comment]
I want to make sure I am linking to the PRs in order to track comments and changes, etc.

Links to PRs for [zeppelin](https://stash.corp.netflix.com/projects/DSEPLAT/repos/commuter-nflx/pull-requests/66/overview) & [clone](https://stash.corp.netflix.com/projects/DSEPLAT/repos/commuter-nflx/pull-requests/67/overview).

**Comment by rgbkrk** [comment]
Looks like we're all set here!
